#!/bin/bash

#Include the default bashrc file
. /etc/skel/.bashrc

#Set the prompt
export PS1="\\[\\033[0;31m\\]\\u:\\w#\\[\\033[0m\\] "

umask 022

#Make file removal interactive by default
alias rm="rm -i"

#If this is the first virtual terminal, then download and run the installer
if tty | grep -q tty1 ; then
  echo 'Attempting to ping sun1.cs.uca.edu'
  if ! ping -c 1 -W 1 sun1.cs.uca.edu > /dev/null ; then
    echo 'Ping failed. Trying to configure eth0!!!'
#    sed 's/allow-hotplug/auto/' /etc/network/interfaces > /tmp/interfaces
#    mv /tmp/interfaces  /etc/network/interfaces

    if ! grep -q eth0 /etc/network/interfaces ; then
        echo -e 'auto eth0\niface eth0 inet dhcp' >> /etc/network/interfaces

    fi

    #See if the cable is plugged in
    if ! ethtool eth0 | grep -q 'Link detected.*yes' ; then
      echo "Network cable is unplugged!!!!!!"
      exit
    fi

    if ! /sbin/ifup -a ; then
      echo "Networking is not functioning!!!!"
    fi

    echo 'Syncing system'
    sync

    #Try pinging again
    if ! ping -c 1 -W 1 sun1.cs.uca.edu > /dev/null ; then
      echo "Failed to bring the network on line!!!"
      exit 1
    fi

  else
      echo 'Network is functioning'
  fi

  #Fetch the file
  if ! wget 'HTTP_CLIENT_SCRIPT' -O - > $HOME/client-install.sh ; then
    if [ -e $HOME/client-install.sh ] ; then
      rm -f $HOME/client-install.sh
    fi
    echo 'Failed to download the client script'
    exit 1
  fi

  #Make sure the download went OK
  if [ -e $HOME/client-install.sh ] ; then
    #Make the file executable
    chmod -v u+x $HOME/client-install.sh

    #Run the script
    $HOME/client-install.sh
  fi
fi
